server:
  port: 8088

spring:
  application:
    name: takeout-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:}
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: http://localhost:8101
          predicates:
            - Path=/api/users/**
        - id: merchant-service
          uri: http://localhost:8102
          predicates:
            - Path=/api/merchant/**
        - id: rider-service
          uri: http://localhost:8103
          predicates:
            - Path=/api/rider/**
        - id: order-service
          uri: http://localhost:8104
          predicates:
            - Path=/api/orders/**
        - id: admin-service
          uri: http://localhost:8105
          predicates:
            - Path=/api/admin/**
